### ISSUE TITLE
Torsocks support and a couple questions

### ISSUE THREAD

**Issue by DigiAngel** [leunammejii/analyst_arsenal#1]
Certstream doesn't allow tor connections.  I'd love to see an option that will allow opendir_certstream to connect over a non-tor connection, but download files over tor.

Next, does opendir_certstream.py rely on both external.yaml and suspicious.yaml?  Thank you.

**Comment by leunammejii** [comment]
I'm new to the technology but after looking at the documentation, adding that option shouldn't be too difficult. I'll try to have something in the coming days.

`opendir_certstream.py` does rely on both files to be present (line 214-221). `suspicious.yaml` is needed to score the domains seen coming through Certstream. `external.yaml` is used to, at a minimum, check for different file types in open directories found. If you want `suspicious.yaml` to override `external.yaml`, then `override_suspicious.yaml` must be set to `true`. Otherwise, you can keep the default settings. I also added some checks for needed dictionaries `files` and `archives`.

**Comment by DigiAngel** [comment]
Excellent...thank you.

**Comment by leunammejii** [comment]
Checkout the update on the `add_tor` branch [here](https://github.com/leunammejii/analyst_arsenal/tree/add_tor).

You should be to download files via Tor if the `--tor` flag is passed. You can also change the timeout with the `--timeout` flag (default: 30).

Let me know what you think. If all is well, I'll merge to the master branch.

**opendir_certstream.py Example:**
```bash
python opendir_certstream.py --tor --timeout=20
```

**opendir_certstream.py Example:**
```bash
python opendir_urlscan.py manual 0 zip --exclude="google.com" --tor --timeout=20
```
![b](https://user-images.githubusercontent.com/12433311/49976859-cb970880-ff11-11e8-8f44-3240f3c12232.png)

**Comment by DigiAngel** [comment]
Excellent thank you...I'll test this out tomorrow and let you know of my results...great work!

**Comment by DigiAngel** [comment]
Works great thank you!
